export const commonActionTypes = {
    SET_SITE_LOGO : 'SET_SITE_LOGO',
    SET_SOCIAL_MEDIA : 'SET_SOCIAL_MEDIA',
    SET_FOOTER_LOGO : 'SET_FOOTER_LOGO',
    SET_COPYRIGHT : 'SET_COPYRIGHT',
    SET_CONTACT_NO : 'SET_CONTACT_NO',
    SET_EMAIL : 'SET_EMAIL',
}