export const homeActionTypes = {
    SET_MAIN_BANNER : 'SET_MAIN_BANNER',
    SET_BANNER_TEXT : 'SET_BANNER_TEXT',
    SET_ABOUT_CONTENT : 'SET_ABOUT_CONTENT',
    SET_ABOUT_IMAGE : 'SET_ABOUT_IMAGE',
    SET_THINGS : 'SET_THINGS',
    SET_TESTIMONIALS : 'SET_TESTIMONIALS',
    SET_CLIENTS : 'SET_CLIENTS',
}